### ISSUE TITLE
Field 'foo' doesn't have a default value

### ISSUE THREAD

**Issue by dreamingmind** [pakacuda/cakephp-fixture-factories#17]
After updating I started getting 'Field 'foo' doesn't have a default value' errors on previously passing tests.

Wasn't the system glossing over errors like this when `make()`ing records? 

After updating to 0.2.14 (that's when I noticed it), tests that were previously running started throwing this error.

My code was in a bit of chaos at that point so I'm not 100% sure about this.

I'm on 0.2.15 now

**Comment by dreamingmind** [comment]
As I look deeper I see both [this section on validation behaior](https://github.com/pakacuda/cakephp-fixture-factories/blob/master/docs/factories.md#validation--behaviors) which says:

>all validations are deactivated when creating CakePHP entities 
>and persisting them to the database.


and the comment on `setDefaultTemplate()`:

```
* Defines the default values of you factory. Useful for
* not nullable fields. You may use methods of the factory here too.
```

So my tests may have been previously passing due to some interaction related to the old cake factories because I had both listeners turned on at that point.

**Comment by pabloelcolombiano** [comment]
let us know, if you are experiencing further issues there.

**Comment by dreamingmind** [comment]
This is an ongoing issue. Where previously I did not have to create any code in `setDefaultTemplate()` now I must define defaults for columns that don't otherwise have them.

**Comment by pabloelcolombiano** [comment]
`setDefaultTemplate()` is there to assign default values of your factory, as you write.

What is the issue you are actually having? Is there anyting we can improve or solve?

**Comment by dreamingmind** [comment]
This is my database schema. It has columns that do not have defaults but are not allowed to be NULL.

<img width="787" alt="Screen Shot 2020-06-04 at 11 41 27 AM" src="https://user-images.githubusercontent.com/1307216/83798409-156d3480-a659-11ea-9ac2-ab56e87479ef.png">

This is my test class:

```
<?php

namespace App\Test\TestCase\Model\Table;

use App\Test\Factory\PersonFactory;

class PeopleTableTest extends \Cake\TestSuite\TestCase
{

    public function testMake()
    {
        $person = PersonFactory::make(1)->persist();
    }
}
```
Running the test results in this error.

<img width="867" alt="Screen Shot 2020-06-04 at 11 47 55 AM" src="https://user-images.githubusercontent.com/1307216/83798552-477e9680-a659-11ea-9e7d-675efc913b5e.png">

My expectation based on the documentation and my previous experience is that the entity could be created without error in this circumstance.

My factory is baked from the most recent version:

<img width="604" alt="Screen Shot 2020-06-04 at 11 50 55 AM" src="https://user-images.githubusercontent.com/1307216/83798936-dee3e980-a659-11ea-90af-f0d3521b5daf.png">

**Comment by pabloelcolombiano** [comment]
I do not know how your caode was before, but this should normally nothave worked before either.

In your case, you should have in your factory:
```
 protected function setDefaultTemplate(): void
    {
        $this->setDefaultData(function(Generator $faker) {
            return [
                'first_name' => $faker->firstName,
                'last_name' => $faker->lastName,
                'role' => $faker->text(50)
            ];
        });
    }
```


Your test could then look like this:
```
class PeopleTableTest extends \Cake\TestSuite\TestCase
{

    public function testMake()
    {
        $person = PersonFactory::make()->persist();
    }
}
```

or like that, if you want to control the value of the field `role`:
```
class PeopleTableTest extends \Cake\TestSuite\TestCase
{

    public function testMake()
    {
        $person = PersonFactory::make(['role' => 'Some role'])->persist();
    }
}
```

Does ths make sense enough?

**Comment by dreamingmind** [comment]
Perfect sense, thanks.
