### ISSUE TITLE
Issue when working with relationship data

### ISSUE THREAD

**Issue by ishan-biztech** [pakacuda/cakephp-fixture-factories#20]
I have two tables:

**src/Model/ProductsTable.php**
```php
<?php
declare(strict_types=1);

namespace App\Model\Table;

...

class ProductsTable extends Table
{
    public function initialize(array $config): void
    {
        ...

        $this->belongsTo('Categories', [
            'foreignKey' => 'category_id',
            'joinType' => 'INNER',
        ]);
    }

    ...
}
```

**src/Model/CategoriesTable.php**
```php
<?php
declare(strict_types=1);

namespace App\Model\Table;

...

class CategoriesTable extends Table
{
    public function initialize(array $config): void
    {
        ...

        $this->belongsTo('ParentCategories', [
            'className' => 'Categories',
            'foreignKey' => 'parent_id',
        ]);
        $this->hasMany('ChildCategories', [
            'className' => 'Categories',
            'foreignKey' => 'parent_id',
        ]);
        $this->hasMany('Products', [
            'foreignKey' => 'category_id',
        ]);
    }

    ...
}

```

Here's my factory files:

**tests/Factory/ProductFactory.php**
```php
<?php
declare(strict_types=1);

namespace App\Test\Factory;

...

class ProductFactory extends CakephpBaseFactory
{
    protected function getRootTableRegistryName(): string
    {
        return 'Products';
    }

    protected function setDefaultTemplate(): void
    {
        $this->setDefaultData(function(Generator $faker) {
            return [
                // set the model's default values
                // For example:
                // 'name' => $faker->lastName
            ];
        });
    }

    public function withCategories(array $parameter = null): ProductFactory
    {
        return $this->with(
            'Categories',
            \App\Test\Factory\CategoryFactory::make($parameter)
        );
    }
}
```

**tests/Factory/CategoryFactory.php**
```php
<?php
declare(strict_types=1);

namespace App\Test\Factory;

...

class CategoryFactory extends CakephpBaseFactory
{
    protected function getRootTableRegistryName(): string
    {
        return 'Categories';
    }

    protected function setDefaultTemplate(): void
    {
        $this->setDefaultData(function(Generator $faker) {
            return [
                // set the model's default values
                // For example:
                // 'name' => $faker->lastName
            ];
        });
    }

    public function withParentCategories(array $parameter = null): CategoryFactory
    {
        return $this->with(
            'ParentCategories',
            \App\Test\Factory\CategoryFactory::make($parameter)
        );
    }

    public function withChildCategories(array $parameter = null, int $n = 1): CategoryFactory
    {
        return $this->with(
            'ChildCategories',
            \App\Test\Factory\CategoryFactory::make($parameter, $n)->without('Category')
        );
    }

    public function withProducts(array $parameter = null, int $n = 1): CategoryFactory
    {
        return $this->with(
            'Products',
            \App\Test\Factory\ProductFactory::make($parameter, $n)->without('Category')
        );
    }
}
```

Now when I try to access product factory with categories, it doesn't seem to work:
```php
$product = ProductFactory::make()->withCategories(1)->getEntity();
```
Above code returns below error:
```bash
TypeError: Argument 1 passed to App\Test\Factory\ProductFactory::withCategories() must be of the type array or null, integer given, called in /var/www/html/prod/cakephp4/tests/TestCase/Controller/ProductsControllerTest.php on line 26
```
I've just baked both factory and haven't changed anything. Also the code I'm using is documented [here](https://github.com/pakacuda/cakephp-fixture-factories/blob/master/docs/examples.md#populating-associations-the-with-method), which seems to be outdated may be.

To fix this I passed `null` in `withCategories` call, then it seems to work. 

But when I add fake data and try to get those it doesn't return related category data in the returned entity result. I might be missing here something don't know but I can't find anything in the documentation to help me with this.

Please suggest the proper way to work with relationship data.

The behavior I want is, when we do `ProductFactory::make()->withCategories(1)->getEntity()` it should create new product entity along with a new category entity and the category entity should auto relate to product entity automatically without doing any more hustle.

**Comment by pabloelcolombiano** [comment]
Thanks for extensively sharing your code.

The 1 you typed as a parameter is not necessary. You get an error because the method `withCategories` accept only arrays as parameters. You can change that in the `ProductFactory,` and 1 should be accepted. But again, 1 being the default value, you can omit it.

I will modify the baked template, in order to remove the array constraint.

>But when I add fake data and try to get those it doesn't return related category data

Did you inject the faked data in the setDefaultTemplate method? Or passed it as arguments to withCategories()? Could you illustrate that with some code?

**Comment by ishan-biztech** [comment]
Yes I've set the fake data in `setDefaultTemplate` method in `ProductFactory` & `CategoryFactory` both. See below:

**ProductFactory.php**:
```php
    protected function setDefaultTemplate(): void
    {
        $this->setDefaultData(function(Generator $faker) {
            return [
                'name' => $faker->text('50'),
                'slug' => $faker->slug,
                'price' => $faker->biasedNumberBetween(1, 99),
                'description' => $faker->text,
            ];
        });
    }

    public function withCategories(array $parameter = null): ProductFactory
    {
        return $this->with(
            'Categories',
            \App\Test\Factory\CategoryFactory::make($parameter)
        );
    }
```

**CategoryFactory.php**
```php
    protected function setDefaultTemplate(): void
    {
        $this->setDefaultData(function(Generator $faker) {
            return [
                'name' => $faker->word,
                'parent_id' => null,
            ];
        });
    }

    public function withProducts(array $parameter = null, int $n = 1): CategoryFactory
    {
        return $this->with(
            'Products',
            \App\Test\Factory\ProductFactory::make($parameter, $n)->without('Category')
        );
    }
```

Now in my test file, I'm calling it like this:

```php
$product = ProductFactory::make()
    ->withCategories(['name' => 'Electronics'])
    ->getEntity();
debug($product);exit;
```

or 

```php
$product = ProductFactory::make()
    ->withCategories()
    ->getEntity();
debug($product);exit;
```

Result is same for both of the above code:

```bash
########## DEBUG ##########
object(App\Model\Entity\Product) {
    'name' => 'Dolores dolorum amet iste laborum eius est dolor.',
    'slug' => 'a-quo-sed-fugit-facilis-perferendis-dolores-molestias',
    'price' => '32',
    'description' => 'Fuga aspernatur natus earum quas. Perferendis voluptatibus incidunt nostrum quia possimus. Id et necessitatibus architecto aut consequatur debitis.',
    '[new]' => true,
    '[accessible]' => [
        'category_id' => true,
        'name' => true,
        'slug' => true,
        'price' => true,
        'description' => true,
        'created' => true,
        'modified' => true,
        'category' => true
    ],
    '[dirty]' => [
        'name' => true,
        'slug' => true,
        'price' => true,
        'description' => true
    ],
    '[original]' => [],
    '[virtual]' => [],
    '[hasErrors]' => false,
    '[errors]' => [],
    '[invalid]' => [],
    '[repository]' => 'Products'
}
###########################
```

As you can see, I don't have any related data from categories even I've used `withCategories` method.

**Comment by pabloelcolombiano** [comment]
What happens if you rename your association `Categories` in `Category` in the `ProductsTable`? According to your model, a `product` belongs to one `category`.

**Comment by ishan-biztech** [comment]
Yes, it works if I change `Categories` to `Category`. But I don't understand why we need to do like this? Is there any particular reason for this? Because all the things are baked, I've not made any changes manually. So it should bake the thing accordingly and return error message saying you should fix plural to singular or whatever error that is.

Also as per the documentation [here](https://github.com/pakacuda/cakephp-fixture-factories/blob/master/docs/examples.md#populating-associations-the-with-method):
1. I assume the `Articles` table is having relation with `Authors` table using `belongsTo` and as per cakephp standards you specify `Authors` while defining relationship not `Author`.
2. Also the doc says `withAuthors` not `withAuthor`, so as per my case it will be `withCategories` not `withCategory`.

I don't know if this is my fault of understanding or is this plugin behaves differently than CakePHP convention?

**Comment by pabloelcolombiano** [comment]
I agree with you, that plural relationships should work for `toOne` relationship. I'll check next week what can be improved, or if this is a CakePHP characteristic. In any case, we intend to stick to the conventions.

Regarding the example you pointed, `articles` can have many `authors`, so having the association named plural is correct. I'll mention that in the docs.

**Comment by pabloelcolombiano** [comment]
I have fixed the issue of non saved plural toOne association.

As described in the documentation here:

https://book.cakephp.org/3/en/orm/saving-data.html#saving-belongsto-associations

the associated data should be singular, which the package did not consider.

This is now fixed, you may update the package with its latest version.

I personally prefer naming my toOne associations singular, but if you don't, feel free rename your associations plural, and please let me know if it worked for you.

I will close this issue in three days, if this alright for you.

**Comment by ishan-biztech** [comment]
Thanks for the update. Will check and let you know.
