### ISSUE TITLE
makeWithModelListenersAndBehaviors should be a transient state change, not permanent

### ISSUE THREAD

**Issue by Zuluru** [pakacuda/cakephp-fixture-factories#23]
`makeWithModelListenersAndBehaviors` as currently implemented sets the `applyListenersAndBehaviors` property of the factory, and leaves it set. I have two concerns with this: one philosophical and one practical.

The philosophical issue is that the function name does not reflect that it will be permanently changing the state. A name like `enableModelListenersAndBehaviorsAndMake` would be clearer about this. But secondly, modern design principles prefer that functions not have two effects; if you need to use "and" to describe what a function does, it should generally be split into two functions.

The practical issue is that if I have `testA` and `testB`, where `testA` calls `makeWithModelListenersAndBehaviors` but `testB` uses only `make`, then the behaviour of `testB` will depend on whether `testA` was run before it or not, because it's not just the concrete factory object that's affected by this, but a static property that `make` references.

**Comment by Zuluru** [comment]
I'm now finding that tests that are testing lifecycle events are failing. Need to be able to:

1. Create a record through the factory without those events
2. Patch the entity and save it
3. Have events like `beforeSave` and `afterSave` run in the table
4. Test then asserts that the events happened and expected effects have been applied

Not sure if I should report this here or as a new issue...

**Comment by pabloelcolombiano** [comment]
What happens if you consider an ArticlesTable and do:

1. `$article = ArticleFactory::make()->getEntity();` // creates an entity, without persisting it. No Model events are triggered.
2. `$ArticlesTable->save($article);` // Save the article the CakePHP regular way.
3. Events Model including `beforeSave` and `afterSave` are triggered by the action in point 2.
4. Assert that you obtained what you expected.

Does this work?

**Comment by Zuluru** [comment]
That would probably work for some scenarios, but many check `isNew` and/or need to reference the entity ID in some way.

**Comment by pabloelcolombiano** [comment]
In that case, how about:

1. `$article = ArticleFactory::make()->persist();` // persists an entity. No Model events are triggered.
2.  Manipulate `$article` at your convenience, e.g. `$article->is_published = true;`
3. `$ArticlesTable->save($article);` // Save the article the CakePHP regular way.
4. Events Model including `beforeSave` and `afterSave` are triggered by the action in point 3.
5. Assert that you obtained what you expected.

Does this work in your new scenario?

The `isNew = true` case is covered by the first scenario (described in the comment above). The `isNew = false` is covered by the scenario in the present comment.

**Comment by Zuluru** [comment]
Yes, this is what I'm doing. But with the recent changes to disable events, step 4 sometimes doesn't happen, because the table has had all those events removed. If I run only the test in question, then it works fine; if I run the entire test suite, then something earlier in the run disables them and they don't get added back. Which is weird, because I thought that Cake makes a fresh table registry for each test.

**Comment by pabloelcolombiano** [comment]
The pacakge does not disable any events. If the method ::make is used, a different TableLocator, cloned on the regular TableLocator is used. But at no time the events of a TableRegistry get removed or added.

The test here illustrates that: https://github.com/pakacuda/cakephp-fixture-factories/blob/master/tests/TestCase/ORM/Locator/FactoryTableLocatorTest.php#L116

I do not know the context in which the issue occurs, but I would suggest isolating the case you are having and possibly propose a test case showing that the package would fails.
