### ISSUE TITLE
Add a way to use the new fixture factories alongside old fixture factories

### ISSUE THREAD

**Issue by pakacuda** [pakacuda/cakephp-fixture-factories#3]
People working on a project that already has cakephp fixtures should have a way to use the factories without rewriting all their fixtures first.
Because the FixtureInjector and FixtureManager provided with this package don't offer a way to deal with both kind of fixtures, this could repel many people from giving it a try and also to just let them progressively convert their project to use the fixture factories.

**Comment by pabloelcolombiano** [comment]
I think we should do as we did at B-projects: introduce a trait that specifies which Fixture injector and Manager to use.
Having Test classes with "mixed" test methods would be confusing any way for the developer.
Do you agree?

**Comment by pakacuda** [comment]
Yes, test classes with mixed fixtures (legacy and factories) should be
prohibited/unsupported.
The documentation should clearly state that.
A trait should do it.
So we should create a second pair of fixture manager and fixture injector
for the mixed mode.

**Comment by pabloelcolombiano** [comment]
Couldn't we have a single pair of manager/injector, that handles both, legacy and factories? We don't have to prohibit legacy, even in the long run.

**Comment by pakacuda** [comment]
That's not prohibiting legacy, even in the log run
I'm just concerned about performance here

**Comment by pabloelcolombiano** [comment]
I propose a solution in the hybrid_fixture_injection branch. I simply check if the test class has any fixtures declared. If this is the case, `parent::startTest($test);` is called.

I wrote a few tests to check that things were working as expected. It looks O.K.

**Comment by pakacuda** [comment]
What if you mix both kind of factories in the same class ?
Are there side effects ?
Should an exception be thrown to let the developer know he might get
unexpected results doing that ?

**Comment by pabloelcolombiano** [comment]
I do not see any side effects if mixing both kind of fixtures. It even present a minor advantage.

You could use cake fixtures to set your DB schema, so you do not have to run any migrations, and populate your test DB with pakacuda fixtures.

It is definitely not my prefered approach, because you still have to maintain cake fixtures. But my tests show it is O.K. to do that.

It smoothes the the migration fronm cake to pakacuda fixtures.

**Comment by pabloelcolombiano** [comment]
Both Cakephp and Cakephp Fixture Factories can be used in parallel. It is however recommended for performance and speed issues to use the factories only.
