### ISSUE TITLE
Handle the branch switching issue on migration

### ISSUE THREAD

**Issue by pabloelcolombiano** [pakacuda/cakephp-fixture-factories#6]
Since the FixtureManager truncates all tables excluding phinxlog, the schema needs to be updatable after switching to a different git branch.

One possibility is to add the option (somewhere to be defined) to truncate the phinxlog as well, so the schema may be rebuild from scratch.

This issue is the same for the test DB as well as for the normal DB. We could search for a general solution to rollback / migrate the migrations from one branch to the other.

**Comment by pabloelcolombiano** [comment]
This describes the problem in Cake:
https://github.com/cakephp/phinx/issues/206

This is a solution for Laravel:
https://github.com/gilbitron/laravel-migrate-to-branch

**Comment by pakacuda** [comment]
the laravel solution is for the application's database, not the test database from what I understand. We should focus on the test database. 
Just deleting all tables and running all the migrations on an empty database is enough at the beginning of the test suite IMO.

**Comment by pabloelcolombiano** [comment]
The Migrator now handles the problem of migratiosn "up" and "missing".
